name: Test how to run a specific file from a branch using GitHub Actions

on:
  label:
    types:
      - created
      - edited
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yaml'

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo statement
        run: echo "Hello World"