name: Test how to run a specific file from a branch using GitHub Actions

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yaml'
      - 'README.md'

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo statement
        run: echo "Hello World"