name: Test how to run a specific file from a branch using GitHub Actions

on:
  push:
    branches: [ develop ]
    paths-ignore: 
      # - '.github/workflows/test.yaml' 
      - '.github/workflows/cicd_pipeline.yaml' 
    

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo statement
        run: echo "Hello World"